
export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash-preview-04-17';

export const REPORT_DISCLAIMER = `\n\n---\n\n**Disclaimer:** This report is generated by an AI model using the provided documents and its knowledge base. It is for informational purposes only and does not constitute legal advice, nor is it a substitute for a professional patent search or legal opinion from a qualified patent attorney. The accuracy and completeness of the information cannot be guaranteed. Always consult with a qualified professional for decisions regarding patentability, freedom to operate, or intellectual property strategy.`;

export const MAX_FILE_SIZE_MB = 10;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

export const ACCEPTED_FILE_TYPES = {
  'text/plain': ['.txt'],
  'text/markdown': ['.md'],
  'application/pdf': ['.pdf'],
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
};

export const TOKEN_WARNING_THRESHOLD = 800000; // Threshold for combined prompt (template + user content)
