

export const GEMINI_MODEL_TEXT = 'gemini-2.5-flash';

export const MAX_FILE_SIZE_MB = 10;
export const MAX_FILE_SIZE_BYTES = MAX_FILE_SIZE_MB * 1024 * 1024;

export const ACCEPTED_FILE_TYPES = {
  'text/plain': ['.txt'],
  'text/markdown': ['.md'],
  'application/pdf': ['.pdf'],
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': ['.docx'],
};

export const REPORT_DISCLAIMER = `
---
**Disclaimer:** This report is generated by an AI model and is for informational purposes only. It is not legal advice and does not create an attorney-client relationship. You should consult with a qualified patent attorney for professional advice regarding your specific situation. The analysis is based on the information provided and publicly available data at the time of generation, and may not be complete, accurate, or up-to-date.
`;
